### ISSUE TITLE
Implement cloudflare worker for getting favicon of websites

### ISSUE THREAD

**Issue by vedantnn71** [withbeacon/beacon#43]

**Comment by epicadidash** [comment]
@vedantnn71 why would you use a cloudfare worker for this ?

**Comment by vedantnn71** [comment]
Currently, favicons are messed up. I use cheerio which queries the link with a rel attribute set to an icon, which does not quite work on all the sites.

And the major caveat is that it is super slow. It converts the favicon to a blob which costs a lot of performance.

So I am thinking of removing all that crap and building a Cloudflare worker which grabs the favicon directly without converting it and returns it.
